### ISSUE TITLE
Missing training datasets

### ISSUE THREAD

**Issue by pbonte** [dmpalyvos/debs-2020-challenge-local#1]
Hi,

Is it possible that the initial dataset are missing in the 'dataset' folder? 

KR,
Pieter

**Comment by dmpalyvos** [comment]
Hi Pieter,

The dataset will not be published in this repository. It will instead be available to participants after registering in HotCRP. More details [here](https://2020.debs.org/callforgrandchallengesolutions/).

Kind regards,
Dimitris

**Comment by vincenzo-gulisano** [comment]
Dear Pieter,

In order to get access to the initial dataset, it is sufficient to start a new submission, register the members of the team as authors and submit an interims title for your work. Participants are not requested to submit a PDF at this stage. The link at which you can provide this information is: https://debs2020gc.hotcrp.com/ 

Cheers,
Vincenzo
