### ISSUE TITLE
Request for Deadline Extension for Code Submission

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge-local#12]
Hi,
    I am wonderring if you are going to postpone the deadline of code submission due to the outbreak of Covid-19? We are having difficulty on scheduled progress in this situation.

Thanks,
Zongshun Zhang

**Comment by vincenzo-gulisano** [comment]
Dear Zongshun Zhang,
we can extend the current final deadline for code submission given the current situation. Nonetheless, we strongly recommend all participants to submit a preliminary version of their solution before the current deadline, in order for us to have up-to-date participation figures.

Please remember that in order to enter the contest officially and get your system evaluated on our platform, you need to do the following:
1) Register at docker hub (free) and push your container to docker hub. The image must be publicly available so that our system can pull the container without authentication. Choose a unique name as your id and image that does not disclose your identity and cannot be easily found to avoid having competitors potentially looking and analyzing your image.
2) Send to vincenzo.gulisano@chalmers.se, palyvos@chalmers.se and hannajd@chalmers.se your team name (which will later appear on the leaderboard), and the URL to the previously pushed docker image. If you have not yet shared your URL, please do it as soon as possible in order for the evaluation platform to start checking your solution.

**Comment by Zongshun96** [comment]
So, that is saying you would potentially decide an extension after receiving some solutions? How much more time would we be able to get?

Thanks,

**Comment by jin-qin** [comment]
@vincenzo-gulisano Our team also need to postpone the deadline due to the coronavirus. Would you mind extend it? That will be very helpful since we can only work online right now. Thank you so much.

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
We will circulate information about the extension via mail soon.
Thanks
