### ISSUE TITLE
Understanding Evaluation of Q2

### ISSUE THREAD

**Issue by Zongshun96** [dmpalyvos/debs-2020-challenge-local#17]
Hi,

(it looks like the grader repository was not as active as this one, so I re-open the same topic here. Thanks!)

May you illustrate the evaluation logic of Q2 in a graphical way? I was having a hard time to understand the variables, t_out, t_in, t_out' and t_in'.
It looks like t_in causes t_out to be generated. t_in is a data point of power values, t_out is an event detection result.
But then I cannot understand the next sentence,

t_in' the latest input tuple retrieved by a submitted solution when the output tuple t_out' is produced"

Here, what is the "submitted solution"?
What are the "in" and "out" relative to? Is it the grader or our solution?

Also, I didn't see rank_2 and rank_3 in the source code comment. As there are rank_0 and rank_1 in the comment, so I guess some code is missing here?

One more thing is that there isn't a out.csv for Q2 evaluation. Does that mean we only care the deviation from the result of our Q2 solution to that of sample solution of Q1 in out.csv?
This make sense as the sample solution seems to drop all the out of order records and we would be able to tune a good drop ratio to get good accuracy.

Thanks,
Zongshun Zhang

**Comment by vincenzo-gulisano** [comment]
Notice there is a typo (being updated right now) since max(0,1 - abs( t’out.event_s - t’out.event_s ) should be max(0,1 - abs( tout.event_s - t’out.event_s )
 
The evaluation for Query 2 is done assuming a baseline that gets all data in order and, before getting batch i+1 (GET) returns the result for batch i (POST). Since all the data is received in order, such a baseline can get the highest score, because it can provide each exact answer (max accuracy) immediately (max timeliness).
 
The sentence:  “t_in' the latest input tuple retrieved by a submitted solution when the output tuple t_out' is produced” implies your solution might produce the output tuple t_out' (which is Query 2 counterpart of the baseline’s tout) when getting the batch containing t_in' instead of t_in (baseline). In this case, t_in' comes after t_in. 

If we re-write the text using sub-indexes, it would read like this:
 
More concretely, being:
·  out_m the expected tuple produced by a baseline that is fed with all input data in order upon processing of input tuple in_m, and
·  in’_n the latest input tuple retrieved by a submitted solution when the output tuple out’_m is produced, with n>=m,
The timeliness of each output tuple out’_m is computed as: max(0,1 - ( in’_n.i - in_m.i ) / 10.0).
The accuracy is computed, for output tuples in which an event is detected by the baseline as: max(0,1 - abs( out_m.event_s – out’_m.event_s ) / 10.0). 

Notice there is no code missing, the comments refer to timeliness and accuracy as rank_0 and rank_1 of query 2.  When it comes to the missing out.csv, this is because the baseline in the given datasets if Query 1 fed with the same exact data, which would produce an identical out.csv.
