### ISSUE TITLE
Third party libraries

### ISSUE THREAD

**Issue by sayyadabdi** [dmpalyvos/debs-2020-challenge-local#2]
Hi,
I would like to inquire whether we should write the programs from scratch, or we can use third party solutions/libraries/engines such as Kafka or Spark in order to solve the given problems?

**Comment by vincenzo-gulisano** [comment]
Hi,
there are no restrictions on the tools you can use. A solution building on Kafka and/or Spark is fine. Cheers, Vincenzo

**Comment by vincenzo-gulisano** [comment]
Also,
remember that in order to get access to the initial dataset, it is sufficient to start a new submission, register the members of the team as authors and submit an interims title for your work. Participants are not requested to submit a PDF at this stage. The link at which you can provide this information is: https://debs2020gc.hotcrp.com/
Cheers,
Vincenzo

**Comment by sayyadabdi** [comment]
Thanks for your help.
