### ISSUE TITLE
Need clarification for Q2

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#20]
In baseline codes, it seems the events detected by Q2 are not the same as `out.csv`, would you mind give more clarification for it? Can the baseline codes be able to detect the events in `out.csv`? Many thanks.

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
Dear Jing Qin,
you are right in that the results produced by Q2 are not the same as the ones found in `out.csv`. This is because Q2 is fed out-of-order data (also with missing tuples) and the strategy it adopts is to not wait for any late arrival and fill any missing piece of data with a default value. In general, `out.csv` represents the best possible result you can get for Q2 (because it is the result from Q1, the one in which all data comes in order).

The Q2 we provide is just a sample baseline, your version of Q2 can of course adopt any other strategy to provide its output (e.g., wait for late arrivals, if you wish).

**Comment by jin-qin** [comment]
Dear Vincenzo,
Thank you for your reply. Does that mean the `out.csv` still be the baseline for Q2 since I saw the accuracy from the baseline codes is 0, we should follow the `out.csv` for Q2 right?

---
Best regards,
Jing Qin

**Comment by vincenzo-gulisano** [comment]
Dear Jing Qin,
yes, the `out.csv` you find in the shared datasets is what is used to evaluate the output your solution provides for Q2.

**Comment by jin-qin** [comment]
Many thanks, it makes sense to us.
