### ISSUE TITLE
Need clarification for timeliness in Q2

### ISSUE THREAD

**Issue by jin-qin** [dmpalyvos/debs-2020-challenge-local#26]
Would you mind clarifying why the rank goes higher with timeliness?

---
Best regards,
Jing Qin

**Comment by mhendrick98** [comment]
Following up on this - is it that the lower the timeliness scores the better, or do we want a higher one? I noticed the given python solution is quite slow for query 2, but has a high timeliness score. I assume that means we want to aim for a lower one?

Thanks,
Michael

**Comment by vincenzo-gulisano** [comment]
You want a high timeliness score. The baseline solution for query 2 has high timeliness because it immediately provides an answer for a batch as soon as the latter is retrieved. On the other hand, the accuracy score is not good because the missing or late date is simply replaced with a constant (which is a really naive strategy).

**Comment by mhendrick98** [comment]
I see this makes sense - thank you!

**Comment by jin-qin** [comment]
Make sense, thank you so much!
